name: azure

on:
  workflow_dispatch:
jobs:

  terraform:
 
    runs-on: self-hosted

    steps:
 
      - uses: actions/checkout@v4
     
      - name: Run a one-line script
        run: echo Hello, world!

      - name: azure login
        run:  az login --service-principal --username 41526ad7-ed0e-4538-bd33-2e65e458734b --password 0rF8Q~zeV3xzN6KVQ5jkP5QTvkA.LYR746MdgaVO --tenant dad9b541-ed1b-46b6-87db-4a65e300f324
              

  
        
