name: azure

on:
  workflow_dispatch:
jobs:

  terraform:
 
    runs-on: self-hosted

    steps:
 
      - uses: actions/checkout@v4
        
      - name: init
        run: terraform init  
        
      - name: plan
        run: terraform plan

      - name: apply
        run: terraform apply -auto-approve

        

  
        
